version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
    env_file:
      - ./.env_example
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=marik
      - POSTGRES_PASSWORD=marik_password
      - POSTGRES_DB=blog_melle_django

volumes:
  postgres_data:


